//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPUGyro.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPUGyro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n1 {
            get {
                object obj = ResourceManager.GetObject("n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n2 {
            get {
                object obj = ResourceManager.GetObject("n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n3 {
            get {
                object obj = ResourceManager.GetObject("n3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на time	γx1	Ψx1	θx1
        ///0.0137	0.000035 0.00005	-0.00019
        ///0.0274	0.0002	0.0003	-0.0012
        ///0.0411	0.0011	0.0016	-0.0061
        ///0.0548	0.0054	0.0077	-0.0309
        ///0.0685	0.0293	0.0370	-0.1552
        ///0.0822	0.1745	0.1233	-0.7270
        ///0.0959	0.3796	0.1020	-1.4367
        ///0.1096	0.5302	-0.0668	-2.2010
        ///0.1233	0.5017	-0.3301	-3.1090
        ///0.137	0.2557	-0.4603	-4.0939
        ///0.1507	0.0169	-0.3595	-5.0041
        ///0.1644	-0.0480	-0.1196	-5.8598
        ///0.1781	0.1093	0.0983	-6.7740
        ///0.1918	0.3725	0.1054	-7.6924
        ///0.2055	0.5418	-0.1070	-8.6191
        ///0.2192	0.4747	-0.3645	-9.5398
        ///0.2 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string nx1 {
            get {
                return ResourceManager.GetString("nx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на γy1 Ψy1	θy1
        ///0.000035 0.00005 -0.00019
        ///0.0002 0.0003 -0.0012
        ///0.0011 0.0017 -0.0062
        ///0.0058 0.0085 -0.0310
        ///0.0314 0.0407 -0.1558
        ///0.1889 0.1365 -0.7321
        ///0.4130 0.1142 -1.4496
        ///0.5768 -0.0702 -2.2181
        ///0.5436 -0.3572 -3.1316
        ///0.2688 -0.4940 -4.1394
        ///0.0107 -0.3742 -5.0668
        ///-0.0464 -0.1095 -5.9244
        ///0.1378 0.1184 -6.8452
        ///0.4250 0.1080 -7.7735
        ///0.5931 -0.1359 -8.7022
        ///0.4971 -0.4103 -9.6374
        ///0.1903 -0.4848 -10.6690
        ///-0.0266 -0.3133 -11.5733
        ///-0.0250 -0.0458 -12.4076
        ///0.2068 0.1406 -13.3533
        ///0.4828 0.0678 -14. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ny1 {
            get {
                return ResourceManager.GetString("ny1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на γy1 Ψy1 θy1
        ///0.000035 0.000048 -0.0002
        ///0.0002 0.00028 -0.0012
        ///0.0011 0.0015 -0.0062
        ///0.0056 0.0074 -0.0314
        ///0.0305 0.0353 -0.1575
        ///0.1779 0.1136 -0.7372
        ///0.3788 0.0814 -1.4538
        ///0.5168 -0.0944 -2.2260
        ///0.4683 -0.3517 -3.1527
        ///0.2122 -0.4583 -4.1572
        ///-0.0097 -0.3361 -5.0703
        ///-0.0463 -0.0938 -5.9310
        ///0.1339 0.1011 -6.8613
        ///0.3922 0.0733 -7.7890
        ///0.5280 -0.1580 -8.7239
        ///0.4197 -0.3988 -9.6724
        ///0.1397 -0.4444 -10.6951
        ///-0.0408 -0.2761 -11.5872
        ///-0.0218 -0.0343 -12.4278
        ///0.2009 0.1172 -13.3815
        ///0.4440 0.0310 -1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string nz1 {
            get {
                return ResourceManager.GetString("nz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ort {
            get {
                object obj = ResourceManager.GetObject("Ort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на time γx0 γy0 γz0 Ψx0 Ψy0 Ψz0 θx0 θy0 θz0    			
        ///0.01 0.3105 0.2806 0.3539 -0.3790 -0.2075 -0.3706 -1.7293 -1.5824 -1.6820
        ///0.02 -0.1599 0.0450 -0.1208 -0.5796 -0.4757 -0.6306 -3.7029 -3.2659 -3.6359
        ///0.03 -0.2604 -0.2146 -0.2964 -0.0994 -0.2142 -0.1352 -5.5627 -4.9766 -5.5108
        ///0.04 0.2695 0.0701 0.2644 -0.1050 0.0114 -0.0581 -7.2440 -6.5445 -7.1482
        ///0.05 0.1338 0.2898 0.2434 -0.6220 -0.2779 -0.6227 -9.0639 -8.1279 -8.8880
        ///0.06 -0.3549 -0.0317 -0.3529 -0.3201 -0.4761 -0.4219 -11.0784 -9.8444 -10.8461
        ///0.07 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ortog {
            get {
                return ResourceManager.GetString("ortog", resourceCulture);
            }
        }
    }
}
