//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPUGyro.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPUGyro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n1 {
            get {
                object obj = ResourceManager.GetObject("n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n2 {
            get {
                object obj = ResourceManager.GetObject("n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n3 {
            get {
                object obj = ResourceManager.GetObject("n3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на time	γx1	Ψx1	θx1
        ///0.0137	0.000035 0.00005	-0.00019
        ///0.0274	0.0002	0.0003	-0.0012
        ///0.0411	0.0011	0.0016	-0.0061
        ///0.0548	0.0054	0.0077	-0.0309
        ///0.0685	0.0293	0.0370	-0.1552
        ///0.0822	0.1745	0.1233	-0.7270
        ///0.0959	0.3796	0.1020	-1.4367
        ///0.1096	0.5302	-0.0668	-2.2010
        ///0.1233	0.5017	-0.3301	-3.1090
        ///0.137	0.2557	-0.4603	-4.0939
        ///0.1507	0.0169	-0.3595	-5.0041
        ///0.1644	-0.0480	-0.1196	-5.8598
        ///0.1781	0.1093	0.0983	-6.7740
        ///0.1918	0.3725	0.1054	-7.6924
        ///0.2055	0.5418	-0.1070	-8.6191
        ///0.2192	0.4747	-0.3645	-9.5398
        ///0.2 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string nx1 {
            get {
                return ResourceManager.GetString("nx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на γy1 Ψy1	θy1
        ///0.000035 0.00005 -0.00019
        ///0.0002 0.0003 -0.0012
        ///0.0011 0.0017 -0.0062
        ///0.0058 0.0085 -0.0310
        ///0.0314 0.0407 -0.1558
        ///0.1889 0.1365 -0.7321
        ///0.4130 0.1142 -1.4496
        ///0.5768 -0.0702 -2.2181
        ///0.5436 -0.3572 -3.1316
        ///0.2688 -0.4940 -4.1394
        ///0.0107 -0.3742 -5.0668
        ///-0.0464 -0.1095 -5.9244
        ///0.1378 0.1184 -6.8452
        ///0.4250 0.1080 -7.7735
        ///0.5931 -0.1359 -8.7022
        ///0.4971 -0.4103 -9.6374
        ///0.1903 -0.4848 -10.6690
        ///-0.0266 -0.3133 -11.5733
        ///-0.0250 -0.0458 -12.4076
        ///0.2068 0.1406 -13.3533
        ///0.4828 0.0678 -14. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ny1 {
            get {
                return ResourceManager.GetString("ny1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на γy1 Ψy1 θy1
        ///0.000035 0.000048 -0.0002
        ///0.0002 0.00028 -0.0012
        ///0.0011 0.0015 -0.0062
        ///0.0056 0.0074 -0.0314
        ///0.0305 0.0353 -0.1575
        ///0.1779 0.1136 -0.7372
        ///0.3788 0.0814 -1.4538
        ///0.5168 -0.0944 -2.2260
        ///0.4683 -0.3517 -3.1527
        ///0.2122 -0.4583 -4.1572
        ///-0.0097 -0.3361 -5.0703
        ///-0.0463 -0.0938 -5.9310
        ///0.1339 0.1011 -6.8613
        ///0.3922 0.0733 -7.7890
        ///0.5280 -0.1580 -8.7239
        ///0.4197 -0.3988 -9.6724
        ///0.1397 -0.4444 -10.6951
        ///-0.0408 -0.2761 -11.5872
        ///-0.0218 -0.0343 -12.4278
        ///0.2009 0.1172 -13.3815
        ///0.4440 0.0310 -1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string nz1 {
            get {
                return ResourceManager.GetString("nz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ort {
            get {
                object obj = ResourceManager.GetObject("Ort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на time γx0 γy0 γz0 Ψx0 Ψy0 Ψz0 θx0 θy0 θz0    			
        ///0.01 0.3105 0.2806 0.3539 -0.3790 -0.2075 -0.3706 -1.7293 -1.5824 -1.6820
        ///0.02 -0.1599 0.0450 -0.1208 -0.5796 -0.4757 -0.6306 -3.7029 -3.2659 -3.6359
        ///0.03 -0.2604 -0.2146 -0.2964 -0.0994 -0.2142 -0.1352 -5.5627 -4.9766 -5.5108
        ///0.04 0.2695 0.0701 0.2644 -0.1050 0.0114 -0.0581 -7.2440 -6.5445 -7.1482
        ///0.05 0.1338 0.2898 0.2434 -0.6220 -0.2779 -0.6227 -9.0639 -8.1279 -8.8880
        ///0.06 -0.3549 -0.0317 -0.3529 -0.3201 -0.4761 -0.4219 -11.0784 -9.8444 -10.8461
        ///0.07 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ortog {
            get {
                return ResourceManager.GetString("ortog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0,3105
        ///-0,1599
        ///-0,2604
        ///0,2695
        ///0,1338
        ///-0,3549
        ///0,0578
        ///0,3192
        ///-0,2131
        ///-0,2266
        ///0,3058
        ///0,0772
        ///-0,3609
        ///0,0981
        ///0,3110
        ///-0,2457
        ///-0,1905
        ///0,3204
        ///0,0282
        ///-0,3627
        ///0,1323
        ///0,3011
        ///-0,2760
        ///-0,1568
        ///0,3334
        ///-0,0164
        ///-0,3662
        ///0,1681
        ///0,2929
        ///-0,3137
        ///-0,1211
        ///0,3522
        ///-0,0650
        ///-0,3736
        ///0,2113
        ///0,2867
        ///-0,3703
        ///-0,0770
        ///0,3850
        ///-0,1270
        ///-0,3859
        ///0,2714
        ///0,2815
        ///-0,4766
        ///-0,0065
        ///0,4544
        ///-0,2171
        ///-0,3832
        ///0,3626
        ///0,2469
        ///-0,3406
        ///0,0498
        ///0,3080
        ///-0,2028
        ///-0,2232
        ///0,2945
        ///0,0790
        ///-0,3532
        ///0,0960
        ///0,3039
        ///-0, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ortog_kren_x {
            get {
                return ResourceManager.GetString("ortog_kren_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0,2806
        ///0,0450
        ///-0,2146
        ///0,0701
        ///0,2898
        ///-0,0317
        ///-0,2078
        ///0,1388
        ///0,2797
        ///-0,1029
        ///-0,1799
        ///0,2004
        ///0,2474
        ///-0,1630
        ///-0,1322
        ///0,2517
        ///0,1923
        ///-0,2095
        ///-0,0678
        ///0,2915
        ///0,1177
        ///-0,2399
        ///0,0084
        ///0,3176
        ///0,0308
        ///-0,2513
        ///0,0889
        ///0,3264
        ///-0,0571
        ///-0,2403
        ///0,1659
        ///0,3129
        ///-0,1357
        ///-0,2049
        ///0,2325
        ///0,2729
        ///-0,2001
        ///-0,1474
        ///0,2869
        ///0,2065
        ///-0,2494
        ///-0,0713
        ///0,3297
        ///0,1173
        ///-0,2809
        ///0,0171
        ///0,3578
        ///0,0152
        ///-0,2916
        ///0,1087
        ///0,3672
        ///-0,0845
        ///-0,2765
        ///0,1940
        ///0,3509
        ///-0,1695
        ///-0,2333
        ///0,2647
        ///0,3031
        ///-0,2373
        ///-0,166 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ortog_kren_y {
            get {
                return ResourceManager.GetString("ortog_kren_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0,3539
        ///-0,1208
        ///-0,2964
        ///0,2644
        ///0,2434
        ///-0,3529
        ///-0,0183
        ///0,3839
        ///-0,1175
        ///-0,3392
        ///0,2707
        ///0,2922
        ///-0,3837
        ///-0,0460
        ///0,4203
        ///-0,1100
        ///-0,3999
        ///0,2681
        ///0,3650
        ///-0,3809
        ///-0,1059
        ///0,4352
        ///-0,0574
        ///-0,4500
        ///0,1997
        ///0,4336
        ///-0,2551
        ///-0,2090
        ///0,3588
        ///0,1029
        ///-0,3710
        ///0,0870
        ///0,3730
        ///-0,2009
        ///-0,2513
        ///0,3241
        ///0,1688
        ///-0,3682
        ///0,0553
        ///0,3783
        ///-0,1780
        ///-0,2794
        ///0,3120
        ///0,2075
        ///-0,3803
        ///0,0339
        ///0,3956
        ///-0,1676
        ///-0,3113
        ///0,3110
        ///0,2468
        ///-0,4080
        ///0,0164
        ///0,4263
        ///-0,1669
        ///-0,3545
        ///0,3193
        ///0,2979
        ///-0,4712
        ///0,00064
        ///0, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ortog_kren_z {
            get {
                return ResourceManager.GetString("ortog_kren_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0,01
        ///0,02
        ///0,03
        ///0,04
        ///0,05
        ///0,06
        ///0,07
        ///0,08
        ///0,09
        ///0,10
        ///0,11
        ///0,12
        ///0,13
        ///0,14
        ///0,15
        ///0,16
        ///0,17
        ///0,18
        ///0,19
        ///0,20
        ///0,21
        ///0,22
        ///0,23
        ///0,24
        ///0,25
        ///0,26
        ///0,27
        ///0,28
        ///0,29
        ///0,30
        ///0,31
        ///0,32
        ///0,33
        ///0,34
        ///0,35
        ///0,36
        ///0,37
        ///0,38
        ///0,39
        ///0,40
        ///0,41
        ///0,42
        ///0,43
        ///0,44
        ///0,45
        ///0,46
        ///0,47
        ///0,48
        ///0,49
        ///0,50
        ///0,51
        ///0,52
        ///0,53
        ///0,54
        ///0,55
        ///0,56
        ///0,57
        ///0,58
        ///0,59
        ///0,60
        ///0,61
        ///0,62
        ///0,63
        ///0,64
        ///0,65
        ///0,66
        ///0,67
        ///0,68
        ///0,69
        ///0,70
        ///0,71
        ///0,72
        ///0,73
        ///0,74
        ///0,75
        ///0,76
        ///0,77
        ///0,78
        ///0,79
        ///0,80
        ///0,81
        ///0,82
        ///0,83
        ///0,84
        ///0,85
        ///0, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ortog_time {
            get {
                return ResourceManager.GetString("ortog_time", resourceCulture);
            }
        }
    }
}
